name: zodgame

on:
  schedule:
  - cron: "0 0 * * *"
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip3 install -r ./zodgame/requirements.txt
    - name: Run 
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        ZODGAME_COOKIE: ${{ secrets.ZODGAME_COOKIE }}
      run: |
        python3 ./zodgame/zodgame.py "${{secrets.ZODGAME_COOKIE}}"
    - uses: gautamkrishnar/keepalive-workflow@master
